# One-sticker-per-page (Zebra) — each page IS a sticker

page:
  width_mm: 55.1
  height_mm: 30.2
  margin_mm: { top: 2, right: 2, bottom: 2, left: 2 }

label:
  width_mm: 55.1
  height_mm: 30.2
  padding_mm: { top: 1.5, right: 2, bottom: 1.5, left: 2 }
  show_border: false   # <- no rectangle

text:
  font_name: Times New Roman
  line_spacing: 1.0
  align: center
  line1_size_pt: 14   # LOCATION
  line2_size_pt: 14   # DATE
  line3_size_pt: 14   # SOBA <room>
  line4_size_pt: 22   # SKU (biggest)

lines:
  - field: line1  # LOCATION
    show: true
    bold: true
  - field: line2  # DATE (today)
    show: true
    bold: false
  - field: line3  # SOBA <room>
    show: true
    bold: false
  - field: line4  # SKU
    show: true
    bold: true

behavior:
  mode: page_per_label

word:
  align: center

pdf:
  align: center
