# One-sticker-per-page (Zebra) — each page IS a sticker

page:
  # Sticker page size (from your Word screenshots)
  width_mm: 55.1
  height_mm: 30.2
  margin_mm: { top: 2, right: 2, bottom: 2, left: 2 }

label:
  # Same as page; content will fit inside margins
  width_mm: 55.1
  height_mm: 30.2
  padding_mm: { top: 1.5, right: 2, bottom: 1.5, left: 2 }
  show_border: true   # helpful while calibrating; set false for production

text:
  font_name: Arial
  line_spacing: 1.0
  align: center
  line1_size_pt: 10   # LOCATION
  line2_size_pt: 9    # DATE
  line3_size_pt: 10   # SOBA <room>
  line4_size_pt: 14   # SKU (biggest)

lines:
  - field: line1  # LOCATION
    show: true
    bold: false
  - field: line2  # DATE (today)
    show: true
    bold: false
  - field: line3  # SOBA <room>
    show: true
    bold: false
  - field: line4  # SKU
    show: true
    bold: true

behavior:
  mode: page_per_label  # 1 tiny page per sticker

word:
  align: center  # center the table on the page

pdf:
  align: center  # same centering in PDF
